baseURL = 'https://nerdyc.com/'
languageCode = 'en-us'
title = 'Christian Niles'
disableKinds = ["taxonomy", "term"]

[frontmatter]
date = ["date", ":filename"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[permalinks]
  [permalinks.page]
    blog = "/blog/:year/:month/:day/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
